### ISSUE TITLE
acme dashboard new items

### ISSUE THREAD

**Issue by mattben** [ACME-OUI/acme-web-fe#135]
work with @jfharney and @jbeezley to implement and add in cdatweb and the classic viewer to the dashboard and see #136 #134

**Comment by sterlingbaldwin** [comment]
Where is the latest version of the Classic Viewer code @jfharney ?

**Comment by mattben** [comment]
is this the working repo? https://github.com/jfharney/DiagnosticsViewer

**Comment by jfharney** [comment]
Thats the one

**Comment by sterlingbaldwin** [comment]
Is this running live somewhere?

**Comment by jfharney** [comment]
Brian took it down for the week because he is working on the uvcmetrics package (the underlying diagnostics processing engine for cv).  
I am currently rewriting it anyway to be compatible with django 1.8.  It was originally written for django version 1.5 and below.  Also going to trim out the beta exploratory analysis apps like the treeviewer and the heatmap, so that it can be easier to work with in the N2N UI.
The branch Brian and Brian are working on is called "devel-next".

**Comment by sterlingbaldwin** [comment]
I have the functionality of displaying .png files from velo in the dashboard. The functionality from the classic viewer we need to get working is how it takes the climatologies, runs them through uvcdat, and creates the .png files.

**Comment by jfharney** [comment]
Hey Sterling,

The procedure is outlined here (but this is assuming the diags are run on Rhea, not CADES):

https://acme-climate.atlassian.net/wiki/display/WORKFLOW/ACME+%27Classic+View%27+Diagnostics+User+Guide

**Comment by jfharney** [comment]
To respond to the comment a few weeks ago, the older CV version is running  (and can be linked at the top of the dashboard) here:

http://acme-dev-2.ornl.gov/exploratory_analysis/

Newer version to be released soon

**Comment by sterlingbaldwin** [comment]
Thanks @jfharney
