### ISSUE TITLE
ajax cleanup

### ISSUE THREAD

**Issue by mattben** [ACME-OUI/acme-web-fe#56]
I'd like to separate JavaScript logic from the service call. @sterlingbaldwin please pull my [ajax-cleanup](https://github.com/mattben/acme-web-fe/tree/ajax-cleanup) branch, and re work all our ajax calls to call `get_data(url, type, jsonStr)`.

Please also remove unused JS files from the repo.

**Comment by chaosphere2112** [comment]
@mattben @sterlingbaldwin You need to have a callback in order to actually get the data. This function isn't going to do anything useful right now.

It'll do something like this:

```
var val = get_data('/endpoint', "GET", "{json:'value'}");
console.log(val) -> "{result:'', data:''}"
```

$.ajax makes an _asynchronous_ call to the endpoint, which means your script will hit the return statement prior to actually getting the data from the endpoint.

``` javascript
function get_csrf() {
    var nameEQ = "csrftoken=";
    var ca = document.cookie.split(';');
    for (var i = 0; i < ca.length; i++) {
        var c = ca[i];
        while (c.charAt(0) == ' ') c = c.substring(1, c.length);
        if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length, c.length);
    }
    return null;
}

function get_data(url, type, jsonObj, callback){
  var csrftoken = get_csrf();

  var jsonObj = new Object;
  jsonObj.result = '';
  jsonObj.data = '';

  var ajax_obj = $.ajax({
    type: type,
    url: url,
    data: {user:jsonStr},
    dataType: 'json',
    success: function(data){
      jsonObj.result = 'success';
      jsonObj.data = data;
    },
    headers: {
        "X-CSRFToken": csrftoken
    },
    complete: function(xhr, status) {
        callback(jsonObj);
    },
    error: function(request, status, error){
      jsonObj.result = 'error';
      var errorObj = new Object;
      errorObj.request = request;
      errorObj.status = status;
      errorObj.error = error;
      var errorStr = JSON.stringify(errorObj);
      jsonObj.data = errorStr;

    }
  });
  return ajax_obj;
}
```

This will allow us to do AJAX calls to CSRF-protected endpoints (get_csrf, headers X-CSRFToken),  will give us the ability to cancel a request if it gets rendered moot (return ajax_obj), and will make it so we actually get the information that we're interested in (callback, complete:)

**Comment by mattben** [comment]
Thanks @chaosphere2112

**Comment by mattben** [comment]
@sterlingbaldwin hows this coming?

**Comment by sterlingbaldwin** [comment]
Its working great. All ajax calls are going through this wrapper now. I had to make some changes to sam script, but everything is working great.
